defaults: &defaults
  working_directory: ~/app
  docker:
    - image: circleci/node:8

version: 2
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM user
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Install dependencies
          command: npm i
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Test
          command: npm t
  publish:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Set NPM user
          command: echo -e $NPMRC > ~/.npmrc
      - run:
          name: Publish to NPM
          command: npx ndsh publish

workflows:
  version: 2
  ci-cd:
    jobs:
      - install:
          context: org-global
      - test:
          requires:
            - install
      - publish:
          context: org-global
          requires:
            - test

experimental:
  notify:
    branches:
      only:
        - master
